export const environment = {
  production: true,
  //LOGIN: 'https://ridemgmtserverip:443/dishaapiserver/rest/qpa/user/login',
 /* LOGIN: '/login',
  //SIGNUP: 'https://ridemgmtserverip:443/dishaapiserver/rest/qpa/user',
  SIGNUP: '/user',
  ACTIVATE_USER: '/activateuser',
  RESEND_CODE: '/resend',
  REFERRAL_CODE: '/referralcode',
  SAVE_IMAGE: '/image',
  VEHICAL: '/vehical',
  RIDE_MGMT:'/ridemgmt',
  RIDE_CONNECTIVITY: '/ridecoonectivity',
  ROUTE_MATCHSERVER:'/routematchserver',
  PASSANGER_ROUTE_MATCHSERVER:'/passangerRoutematchserver',
  RIDE_CONN:'/rideConnectvity',
  RIDEMGM:'/ridemgmt',
  USERMGMT:'/userMgmt',
  ROUTE_REPOSITORY:'/routerepository',
   BILLING:'/billing',
  FEEDBACK:'/feedback',
   COMMON:'/commonAPI'
  */
  LOGIN: 'http://localhost/login',
  SIGNUP: 'http://localhost/user',
  ACTIVATE_USER: 'http://localhost/activateuser',
  RESEND_CODE: 'http://localhost/resend',
  REFERRAL_CODE: 'http://localhost/referralcode',
  SAVE_IMAGE: 'http://localhost/image',
  VEHICAL: 'http://localhost/vehical',
  RIDE_MGMT: 'http://localhost/ridemgmt1',
  RIDE_CONNECTIVITY: 'http://localhost/ridecoonectivity',
  ROUTE_MATCHSERVER:'http://localhost/routematchserver1',
  PASSANGER_ROUTE_MATCHSERVER:'http://localhost/passangerRoutematchserver',
  RIDE_CONN:'http://localhost/rideConnectvity',
  RIDEMGM:'http://localhost/ridemgmt',
  USERMGMT:'http://localhost/userMgmt',
  ROUTE_REPOSITORY:'http://localhost/routerepository'
};
